baseurl: '/'
permalink: pretty
title: 'FortunaWood Kft'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'High quality timber products fot competitive price.'

seo:
  meta_og_title: "FortunaWood Kft"
  meta_og_type: "website"
  meta_og_url: "https://fortunawood.co"
  meta_og_image: "https://fortunawood.co/images/photo/custom-bg-1.jpg"
  meta_og_description: "High quality timber products fot competitive price."
  meta_twitter_card: "summary"
  meta_twitter_site: "@fortunawood"
  meta_twitter_creator: "@fortunawood"

collections:
  services:
    output: true
  team:
    output: true
  notes:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md